---

# this playbook is so hacky it's practically a bash script. will fix - just want to see it work atm

- name: Install and configure software on target hosts
  hosts: all
  tasks:
    - name: Install some python stuff
      shell: >
             apt-get -qy update && apt-get -qy install curl git vim python-pip python-docker

    #- name: Install docker
    #  shell: >
    #         curl -sSL https://get.docker.io | bash

    - name: Create docker.service.d
      file: path='/lib/systemd/system/docker.service.d' state=directory

    - name: Create /lib/systemd/system/docker.service.d/kolla.conf
      copy:
        content: "[Service]\nExecStart=\nExecStart=/usr/bin/docker daemon -H fd:// --insecure-registry {{ lookup('env','DPLYR_MGMTNET_IP') }}:5000\nMountFlags=\nMountFlags=shared"
        dest: "/lib/systemd/system/docker.service.d/kolla.conf"
      register: file_create

    - name: Restart docker
      command: systemctl daemon-reload && service docker restart
      when: file_create|changed

    - name: Upgrade docker-py
      command: pip install -U docker-py
      when: file_create|changed

